"""empty message

Revision ID: 49c62afacd13
Revises: 4e769cf1cc50
Create Date: 2023-06-21 14:43:19.622011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49c62afacd13'
down_revision = '4e769cf1cc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('filetype', sa.Enum('image', 'video', 'audio', name='MediaType'), nullable=True))
        batch_op.add_column(sa.Column('collection_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['filename'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'collection', ['collection_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')
        batch_op.drop_column('collection_id')
        batch_op.drop_column('filetype')
        batch_op.drop_column('filename')

    op.create_table('media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('filetype', postgresql.ENUM('image', 'video', 'audio', name='MediaType'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='media_pkey'),
    sa.UniqueConstraint('filename', name='media_filename_key')
    )
    # ### end Alembic commands ###
